

--Create a new Bank Account
CREATE TABLE ACCOUNT 
(
  A_ACCOUNT_NUMBER NUMBER,
  A_ACCOUNT_TYPE VARCHAR2(10) NOT NULL,
  A_ACCOUNT_STATUS VARCHAR2(10) NOT NULL,
  A_ACCOUNT_BALANCE NUMBER NOT NULL,

  CONSTRAINT CHK_ACCT_TYPE 
  CHECK (A_ACCOUNT_TYPE IN ('CHECKING',
  							'SAVINGS',
  							'CUSTODIAL',
  							'IRA')),
  CONSTRAINT CHK_ACCT_STATUS 
  CHECK (A_ACCOUNT_STATUS IN ('ACTIVE',
  							  'INACTIVE')),

  CONSTRAINT PK_ACCOUNT_NUMBER PRIMARY KEY (A_ACCOUNT_NUMBER)
);

COMMIT;


--Create a new Bank Customer
CREATE TABLE CUSTOMER
(
  C_ID NUMBER,
  C_FIRST_NAME VARCHAR2(100) NOT NULL,
  C_LAST_NAME VARCHAR2(100) NOT NULL,
  C_LOGIN_NAME VARCHAR(20) NOT NULL,
  A_ACCOUNT_NUMBER NUMBER,
  C_EMAIL_ADDRESS VARCHAR2(200),
  CONSTRAINT PK_CUSTOMER PRIMARY KEY (C_ID)
);


--Add Foreign Key
ALTER TABLE CUSTOMER ADD CONSTRAINT FK_CUSTOMER_ACCOUNT
FOREIGN KEY (A_ACCOUNT_NUMBER) 
REFERENCES ACCOUNT (A_ACCOUNT_NUMBER);

--Add Hashing
ALTER TABLE ACCOUNT ADD (ACCOUNT_HASH VARCHAR2(50));